export const ADD_PRODUCTO_CARRITO = "ADD_PRODUCTO_CARRITO"
export const ADD_PRODUCTO_CARRITO_OK = "ADD_PRODUCTO_CARRITO_OK"
export const ADD_PRODUCTO_CARRITO_FAIL = "ADD_PRODUCTO_CARRITO_FAIL"

export const DELET_PRODUCTO_CARRITO = "DELET_PRODUCTO_CARRITO"
export const DELET_PRODUCTO_CARRITO_OK = "DELET_PRODUCTO_CARRITO_OK"
export const DELET_PRODUCTO_CARRITO_FAIL = "DELET_PRODUCTO_CARRITO_FAIL"

export const CLEAR_PRODUCTO_CARRITO = "CLEAR_PRODUCTO_CARRITO"
export const CLEAR_PRODUCTO_CARRITO_OK = "CLEAR_PRODUCTO_CARRITO_OK"
export const CLEAR_PRODUCTO_CARRITO_FAIL = "CLEAR_PRODUCTO_CARRITO_FAIL"

export const COMENT_PRODUCTO_CARRITO = "COMENT_PRODUCTO_CARRITO"
export const COMENT_PRODUCTO_CARRITO_OK = "COMENT_PRODUCTO_CARRITO_OK"
export const COMENT_PRODUCTO_CARRITO_FAIL = "COMENT_PRODUCTO_CARRITO_FAIL"

export const DELEIT_COMENT_PRODUCTO_CARRITO = "COMENT_PRODUCTO_CARRITO"
export const DELEIT_COMENT_PRODUCTO_CARRITO_OK = "COMENT_PRODUCTO_CARRITO_OK"
export const DELEIT_COMENT_PRODUCTO_CARRITO_FAIL = "COMENT_PRODUCTO_CARRITO_FAIL"